projects/developer/src/app/system/strikes/component.html, projects/developer/src/app/system/strikes/component.ts
Fixes #159.
UI elements and logic are duplicated from jobs component, adding the buttons inline to the job link on the strike detail page.
=> Issue 159 - Basic controls for strike jobs

docker/nginx-template.conf, docker/nginx.conf
Resolves the issue with `/silo` proxy failing to serve anything when setting `SILO_BACKEND` to an HTTPS fronted Silo instance.
=> Fix for SNI validation

projects/developer/src/app/app.module.ts, projects/developer/src/app/common/components/recipe-graph/component.html, projects/developer/src/app/common/components/recipe-graph/component.ts
Closes #207 
In this PR:
- prevents page scrolling in Firefox when zooming in on graph
- add buttons to fit zoom and recenter
- activate these two features when the page first loads
- adds a slider/buttons for easier zooming
Not going to do:
- delete button on either the node itself or the associated popup - workflow will probably be changing at some point
- dragging a node to a new position results in the popup opening - no way to prevent this with the options currently exposed in ngx-graph (open issue and PR in their repo to address)
=> Issue 207 - recipe editor enhancements

Dockerfile, docker/docker-entrypoint.sh, projects/developer/src/app/app.component.ts, projects/developer/src/app/common/services/app-config.service.ts, projects/developer/src/app/common/services/profile.service.ts, projects/developer/src/app/footer/footer.component.html, projects/developer/src/app/footer/footer.component.ts, projects/developer/src/assets/appConfig.json, projects/developer/src/environments/environment.prod.ts, projects/developer/src/environments/environment.ts
- flattens the auth section in appConfig.json
- redo docker-entrypoint.sh
- Jonathan said we no longer need all the logic for multiple contexts (app will always be at root of webserver endpoint)
- takes all environment variables prefixed with SCALEUI_, removes the prefix, and places it into appConfig.json
- bash is used because I couldn't figure out parameter expansion without it
- app-config.service.ts now just loads anything in appConfig.json, camelCases the key, and loads it into environments.ts
- moves an env var from appConfig.json to the Dockerfile, and installs bash
=> Issue 233 - Pass down environment variables into appConfig.json

projects/developer/src/app/common/services/app-config.service.ts
Left out from #255. The raw values from appConfig.json were used instead of the values after the parsing step.
In the case of primary color, the appConfig.json already has `primaryColor`, but the docker script that converts the env var (`SCALEUI_PRIMARY_COLOR`) leaves it as `primary_color` in the appConfig.json. The loop that merged the values into `environments` also camel cases the keys, so `primary_color` overrides `primaryColor`.
=> Issue 256 - use values injected into the environment file rather than raw values

projects/developer/src/app/configuration/recipe-types/api.model.ts
Closes #262 
`definition` has type any, so this is just adding a simple if-check prior to building condition nodes. The diff is just from alignment.
=> Issue 262 - check if definition exists before looping over nodes

api/handlers/jobs.js, projects/developer/src/app/processing/jobs/api.model.ts, projects/developer/src/app/processing/jobs/component.html, projects/developer/src/app/processing/jobs/details.component.ts
Closes #90
This puts an icon in the jobs table page, as well as opening a warning notification when navigating to the job details page.
=> Issue 90 - notifications and icons for when a job will not be retried

projects/developer/src/app/system/scans/details.component.ts, projects/developer/src/app/system/strikes/component.ts
Removed the `revision_num` to ensure that the most recent version of a recipe is used when triggering a recipe.
=> Remove recipe rev from strikes and scans

projects/developer/src/app/data/feed/component.ts
Discovered on site 9/17. Selecting a data time (ingest vs data) would reset the feed selection. Looks like it was due to the single select dropdown not liking the ngmodel to be an array.
=> Data feed won't keep selected feed

projects/developer/src/app/data/feed/component.ts
The Data Feed chart was holding onto previously selected strike data making it difficult to decipher which data was coming from which strike. Since the chart only allows for selecting one strike at a time, the dataset the chart utilizes should only contain the data for the selected strike. The data feed chart now updates with the proper data when a different strike is selected.
=> Data Feed Data

projects/developer/src/app/configuration/job-types/component.html, projects/developer/src/app/configuration/job-types/component.ts, projects/developer/src/app/navbar/navbar.component.html, projects/developer/src/app/navbar/navbar.component.ts, projects/developer/src/app/processing/jobs/component.html, projects/developer/src/app/processing/jobs/component.ts
Any time a confirm dialog was displayed all of the confirm dialogs were displayed. Had to add a key to each dialog so only the proper one would be displayed.
=> Fixing multiple popups

projects/developer/src/app/app.module.ts, projects/developer/src/app/common/components/recipe-graph/component.html, projects/developer/src/app/common/components/recipe-graph/component.scss, projects/developer/src/app/common/components/recipe-graph/component.ts, projects/developer/src/app/configuration/recipe-types/api.condition.model.ts, projects/developer/src/app/configuration/recipe-types/api.filter.model.ts, projects/developer/src/app/configuration/recipe-types/component.html, projects/developer/src/app/configuration/recipe-types/component.ts, projects/developer/src/app/configuration/recipe-types/condition.component.html, projects/developer/src/app/configuration/recipe-types/condition.component.scss, projects/developer/src/app/configuration/recipe-types/condition.component.spec.ts, projects/developer/src/app/configuration/recipe-types/condition.component.ts, projects/developer/src/app/configuration/recipe-types/filter.component.html, projects/developer/src/app/configuration/recipe-types/filter.component.spec.ts, projects/developer/src/app/configuration/recipe-types/filter.component.ts
Closes #334, #190, #319, and maybe others that I can't find. This is a huge change that will definitely need tested.
**Changes:**
- search bar added to add/remove conditions dialog (to be consistent with jobs & recipes dialogs)
- side/sliding dialog for conditions is majorly reworked
- form change to better organize options available for condition nodes
- dynamically change fields and options based on what is selected (eg, string type only allows certain conditions to be selected)
- labels should be a bit more descriptive now
- filters stay in the accordion, with a "remove filter" only if there is more than 1
- saving the condition can only be done if the form is valid
- editing a condition node is now supported #190 
- click on the node once it's added to the recipe graph, then there …
=> Recipe conditions

projects/developer/src/app/configuration/recipe-types/component.html, projects/developer/src/app/configuration/recipe-types/component.ts
remove auto complete toggle in the UI.  Auto complete is a default and not something that the user needs to select.  Removed from the payload to send to the API as well.
=> Recipe auto update

projects/developer/src/app/system/nodes/component.ts
The nodes menu options were not being reset from the first node in the list to the selected node's options when the menu were opened. The `menu.model` needed to be reset to the current node when the menu was opened.
Finishes #336
=> Issue 336 - Fixing nodes menu issue

projects/developer/src/app/app.component.ts, projects/developer/src/environments/environment.prod.ts, projects/developer/src/environments/environment.ts
Closes #387 
- GeoAXIS was missing the `?next=` param in the URL config
- GeoAXIS had a hardcoded localhost redirect
- Same code for non-form and GeoAXIS path, simplify down to just the special cases for form type
- Expose redirect timeout as config variable, set to 0 by default
=> Issue 387 - Simplify auth path, expose redirect timeout as config, fix ?next= param

projects/developer/src/app/common/components/temporal-filter/component.html, projects/developer/src/app/common/components/temporal-filter/component.scss, projects/developer/src/app/common/components/temporal-filter/component.ts
This should allow using the temporal filter in "live range" mode only.
Template usage:
```html
<dev-temporal-filter
localStorageKey="dashboard-filter"
[liveRangeOnly]="true"
(updated)="onTemporalFilterUpdate($event)">
</dev-temporal-filter>
```
In your component:
```ts
onTemporalFilterUpdate(data: {start: string, end: string}): void {
// this will be fired every 10 seconds with a start/end datetime
}
```
=> Issue 391 - Allow using temporal filter in live range mode only

projects/developer/src/app/common/components/recipe-graph/component.ts, projects/developer/src/app/configuration/recipe-types/component.ts, projects/developer/src/app/configuration/recipe-types/condition.component.ts
Closes #400 and closes #401, hopefully. This will need to be thoroughly tested.
The interface of condition nodes gets changed when adding it as a dependency to another node. This needs to be processed by the model, mainly to ensure the `multiple` is a boolean (happens in the constructor of the model). I think this fixes #401.
Related, if you resaved that condition node, validation would pass after that, as outlined in #401, since it was stripping out the interface block during edit. By properly copying the interface when editing, it should stick around now, fixing #400.
=> Issues 400 and 401 - Ensure condition interface is consistent and not lost during edit

projects/developer/src/app/processing/recipes/details.component.ts
Closes #399.
The API seems a bit funky on this, sometimes it returns status for jobs, sometimes not. I don't think it gives a status for sub recipes though.
See `/v6/recipes/44456/` on alpha, `details.nodes`, each node does not contain a `status` flag.
=> Issue 399 - Merge in job details and recipe details to add fill color properly

projects/developer/src/app/configuration/recipe-types/component.ts
* Sets recipeTypeName in the component to the name returned from the recipeType service createRecipeType function call. This was causing the component to consider the newly created recipe to not have a name and therefore route back to the recipe-types list.
=> Issue 441 - Editing a New Recipe Type

projects/developer/src/app/app.module.ts, projects/developer/src/app/common/components/live-range-selector/component.html, projects/developer/src/app/common/components/live-range-selector/component.scss, projects/developer/src/app/common/components/live-range-selector/component.spec.ts, projects/developer/src/app/common/components/live-range-selector/component.ts, projects/developer/src/app/common/components/temporal-filter/component.html, projects/developer/src/app/common/components/temporal-filter/component.scss, projects/developer/src/app/common/components/temporal-filter/component.ts, projects/developer/src/app/dashboard/component.html, projects/developer/src/app/data/ingest/component.html, projects/developer/src/app/data/ingest/component.ts, projects/developer/src/app/data/ingest/datatable.service.ts, projects/developer/src/app/processing/batches/batches-component.html, projects/developer/src/app/processing/batches/batches-component.ts, projects/developer/src/app/processing/batches/datatable.service.ts, projects/developer/src/app/processing/jobs/component.html, projects/developer/src/app/processing/jobs/component.ts, projects/developer/src/app/processing/jobs/datatable.service.ts, projects/developer/src/app/processing/recipes/component.html, projects/developer/src/app/processing/recipes/component.ts, projects/developer/src/app/processing/recipes/datatable.service.ts, projects/developer/src/app/system/scans/component.html, projects/developer/src/app/system/scans/component.ts, projects/developer/src/app/system/scans/datatable.service.ts
Fixes #445 
I think I've captured everything in that issue, but please test out. Big things to test:
- verify live range on dashboard is working as expected
- data tables:
- data > ingest
- processing > batches, jobs, and recipes
- system > scans
The data tables should have:
- new refresh button (not sure about this design)
- clarify the picker is in UTC (I don't like the label, open to ideas)
- allow the user to select no start and/or no end
- only restriction is not allowing the user to select a start that is past an end
- refreshing with the query params should preserve empty start/end dates
- start/end dates are not persisted at all, except for hitting the browser reload
- these should default to 24 hours when there are no query params
Your dates may be stuck in persistence mode the …
=> Issue 445 - simplify date time and live range pickers

api/handlers/files.js, projects/developer/src/app/processing/batches/batch-workflow/batch-workflow.component.spec.ts, projects/developer/src/app/processing/batches/batch-workflow/create-dataset/create-dataset.component.spec.ts, projects/developer/src/app/processing/batches/batch-workflow/create-dataset/create-dataset.component.ts
* Adds null as recipe type to mocks
* Removes getStepHeader test suite since the method no longer exists
* Fixes component import name in specs
* Moves loading state change above optional, filter options building.
* Replaces map with reduce function to check for null recipe_type values before building recipeTypeOptions array.
=> Issue 464 - Data Files table loading spinner persists

projects/developer/src/app/data/metrics/component.scss
When the sidebar is opened and closed, it increases the z-index, which was hiding the calendar dropdown window beneath the sidebar so it appeared unresponsive.  I increased the z-index for the metricsDateFilter to ensure it stays on top even if the user opens and closes the dropdown window many times.
=> Fixed issue 462 calendars not working in metrics

projects/developer/src/app/dashboard/component.ts
I wasn't able to see that many refreshes locally or on alpha. But I fixed that it was making two calls on init.
Fixes #484
=> Issue 484 - Dashboard Pie Chart Constantly Refreshes When Scale Tab Regains Focus (chrome)

.gitignore, projects/developer/src/app/data/ingest/component.ts, scale.code-workspace
This issue also relates to issue #297 Add label to date/time pickers.  In the data -> ingest records view, the start/stop date/time picker does not directly relate to any of the currently displayed date/time columns.  Instead, it relates to the "last modified" information which is displayed on all other views utilizing the same start/stop date/time filter.  This pull request adds a "last modified" column to the data -> ingest records view to provide a direct reference column.  Fix #297 and fix #303.
=> Issue #303 - Data-ingest records unclear on date/time choice

projects/developer/src/app/common/components/recipe-graph/component.ts
After adding an input file to a sub-recipe in the recipe builder, closing the modal, and reopening it, the input file would disappear.  This is fixed.  Fix #491
=> Issue #491 - setting input file to sub-recipe not working

README.md
Title is pretty self-explanatory: we do not currently have our process for tagging new releases documented anywhere. This adds a section to the README under deployment with steps for tagging a new release.
=> Update README with instructions for tagging a new release

README.md, projects/developer/src/app/app.component.ts, projects/developer/src/app/configuration/recipe-types/api.service.ts, projects/developer/src/app/data/timeline/component.html, projects/developer/src/app/data/timeline/component.scss, projects/developer/src/app/data/timeline/component.ts, projects/developer/src/assets/appConfig.json, proxy.conf.json
fix: Limit timeline to latest revisions, add option for past revisions, close #482
Plus change "omega" to "oarfish" in most locations and set default user permissions to "is staff" for local configurations without auth setup.
=> Issue #482 Limit timeline to latest revisions, add option for past revisions

projects/developer/src/app/configuration/recipe-types/component.ts
Add a new recipe invalid definition error 'INVALID_DEFINITION_JSON' to give better and more understandable feedback to the user when multiple validation errors are found.
=> Issue #450 - Better Error Messages

projects/developer/src/app/data/metrics/component.html, projects/developer/src/app/data/metrics/component.scss, projects/developer/src/app/data/metrics/component.ts, projects/developer/src/app/data/timeline/component.html, projects/developer/src/app/data/timeline/component.scss, projects/developer/src/app/data/timeline/component.ts, projects/developer/src/app/processing/jobs/component.html, projects/developer/src/app/processing/jobs/component.ts
- added checkbox to display or hide deprecated jobs in metrics and timeline
- added an additional action to display or hide deprecated jobs in the pull down for configuration->jobs
- added a warning icon to deprecated jobs in the job table
Addresses the [#1817](https://github.com/ngageoint/scale/issues/1817) issue.
=> Depreciate filter

projects/developer/src/app/app-routing.module.ts, projects/developer/src/app/app.module.ts, projects/developer/src/app/common/components/temporal-filter/component.ts, projects/developer/src/app/common/services/files/api.service.ts, projects/developer/src/app/data/ingest/api.service.ts, projects/developer/src/app/data/ingest/component.html, projects/developer/src/app/data/ingest/component.ts, projects/developer/src/app/data/ingest/details.component.html, projects/developer/src/app/data/ingest/details.component.scss, projects/developer/src/app/data/ingest/details.component.spec.ts, projects/developer/src/app/data/ingest/details.component.ts, projects/developer/src/app/processing/batches/batch-workflow/create-dataset/create-dataset.component.html, projects/developer/src/app/processing/batches/batch-workflow/create-dataset/create-dataset.component.ts
- New page - Ingest File details.  The current ingest files list page allows users to filter ingest files, but clicking on
on a row redirects to the job details page of the ingest job.  Not useful at all.  Now it directs to the
new Ingest Details page which shows all jobs executed against the file.
- Processing Jobs and Ingest Files list pages have a new pad date range button.  Clicking button sets the start day time to midnight,
and the end day time to one second before midnight.  This is useful to avoid the end date based on current time because
the page remembers the filters and you will not see incoming jobs which can cause user confusion.
- Create DataSet fixes and changes
- File type, Mime type, and country filters are now done with API calls.  Previously it was client side …
=> ingest details page and other fixes

projects/developer/src/app/processing/jobs/component.ts
reset page number when date range changes.  This has caused confused multiple times, as it is remember when you leave the page and come back as well.
=> bugfix - reset page number when date range changes
