projects/developer/src/app/processing/jobs/details.component.html
=> #41 link to recipe from job detail view

projects/developer/src/app/system/scans/details.component.ts, projects/developer/src/app/system/strikes/component.ts
=> #35 Duplicate strikes/scans

api/data/job-type-status.json, projects/developer/src/app/configuration/job-types/api.model.ts, projects/developer/src/app/configuration/job-types/component.html, projects/developer/src/app/configuration/job-types/component.spec.ts, projects/developer/src/app/configuration/job-types/component.ts, projects/developer/src/app/dashboard/jobs.service.ts
=> #56 - Unable to make a "favorite" job-type from job details page

projects/developer/src/app/data/metrics/chart.service.ts, projects/developer/src/app/data/metrics/component.ts
=> #61 - Metrics page shows same values for min and max

projects/developer/src/app/dashboard/component.html, projects/developer/src/app/dashboard/component.ts
=> #69 - Red fail donuts for Favorites / All Job Types

Dockerfile, docker/docker-entrypoint.sh, docker/nginx-template.conf, docker/nginx.conf
This fix is for issue https://github.com/ngageoint/scale/issues/1628
=> Fix for mis-matched environment variables to Scale bootstrap

Dockerfile, docker/README.md, docker/docker-entrypoint.sh, docker/nginx-template.conf, docker/nginx.conf
Support needed to reverse proxy to Silo instance deployed under:
https://github.com/ngageoint/scale/issues/1599
=> Add reverse proxy to Silo deployed by Scale

projects/developer/src/app/common/services/app-config.service.ts, projects/developer/src/app/configuration/job-types/create.component.ts, projects/developer/src/app/configuration/job-types/font-awesome.json, projects/developer/src/app/footer/footer.component.html, projects/developer/src/app/footer/footer.component.scss, projects/developer/src/app/footer/footer.component.ts, projects/developer/src/assets/appConfig.json, projects/developer/src/environments/environment.prod.ts, projects/developer/src/environments/environment.ts, tsconfig.json
Add ui version and link for documentation to app footer
fixes #88
=> Issue 88 - Missing link to Scale documentation in new UI

.travis.yml
=> Issue 101 - Travis build error

projects/developer/src/app/system/strikes/component.html
=> Issue #97 - Strike Job Link

projects/developer/src/app/common/components/log-viewer/component.ts
=> Issue 108 - Job execution log

projects/developer/src/app/processing/jobs/api.service.ts, projects/developer/src/app/processing/jobs/component.html, projects/developer/src/app/processing/jobs/component.ts
=> Issue 100 - Can't Sort Jobs Table by Duration

projects/developer/src/app/logo/logo.component.scss
=> Issue 115 - Scale Logo Solid

projects/developer/src/app/common/components/log-viewer/component.scss
=> Issue 127 - log text in dark mode is unreadable

projects/developer/src/app/configuration/job-types/api.model.ts, projects/developer/src/app/configuration/job-types/api.service.ts, projects/developer/src/app/configuration/job-types/component.ts
=> #91 - Validate when unpausing or reactivating

api/data/job-type-details/export-shp2.0.json, api/data/job-type-details/landsat8-atmos-corr2.1.9.json, api/data/job-type-details/landsat8-ortho2.0.json, api/data/recipe-type-details/recipe-type-details-landsat8.json, api/data/recipe-types.json, projects/developer/src/app/common/components/recipe-graph/component.html, projects/developer/src/app/common/components/recipe-graph/component.scss, projects/developer/src/app/common/components/recipe-graph/component.ts, projects/developer/src/app/configuration/recipe-types/api.condition.model.ts, projects/developer/src/app/configuration/recipe-types/component.html, projects/developer/src/app/configuration/recipe-types/component.ts
=> Issue 107 - Recipe editor media types

projects/developer/src/app/processing/jobs/component.html, projects/developer/src/app/processing/jobs/component.scss, projects/developer/src/app/processing/jobs/component.ts
Add list of selected job types to job type filter in jobs table. This should help users keep track of what has been selected (#129).
=> Issue 129 - Jobs list view problems

projects/developer/src/app/data/feed/component.ts
=> Issue 144 - Data Feed Console Error

projects/developer/src/app/system/workspaces/component.html, projects/developer/src/app/system/workspaces/component.ts
=> Issue 151 - S3 workspace secret access key should not be required

projects/developer/src/app/system/strikes/component.html, projects/developer/src/app/system/strikes/component.ts
=> Issue 153 - S3 secret access key for strikes should not be required

projects/developer/src/app/system/scans/details.component.html
=> Issue 154 - Incorrect URL to job details from scan details

docker/nginx-template.conf, docker/nginx.conf
Fixes #149 
HAProxy config is in other repo.
=> Issue 149 - Update HAProxy configuration and Nginx to allow correct headers to pass through to API

projects/developer/src/app/data/ingest/component.ts, projects/developer/src/app/system/workspaces/component.html
=> Issue 158 - Minor Typos/Mistakes

projects/developer/src/app/configuration/recipe-types/component.html, projects/developer/src/app/configuration/recipe-types/component.ts, projects/developer/src/app/system/strikes/component.html, projects/developer/src/app/system/workspaces/api.model.ts, projects/developer/src/app/system/workspaces/component.html
=> Issue 160 - Input label/defaults changes

projects/developer/src/app/configuration/job-types/create.component.scss, projects/developer/src/app/system/nodes/component.scss, projects/developer/src/app/theme/dark-theme.ts, projects/developer/src/app/theme/light-theme.ts
=> Issue 165 - Dark Theme Color Changes

projects/developer/src/assets/themes/dark.css
=> Issue 171 - Metrics color selection in Dark Theme

projects/developer/src/app/data/ingest/component.ts, projects/developer/src/app/processing/batches/component.ts, projects/developer/src/app/processing/jobs/component.ts, projects/developer/src/app/processing/recipes/component.ts
=> Issue 175 - Filtering Lists While On Page Other Than 1 Returns 404 Not Found  

projects/developer/src/app/system/scans/details.component.html
=> Issue 167 - Scan job link doesn't go to details

projects/developer/src/app/system/scans/component.html, projects/developer/src/app/system/scans/component.scss, projects/developer/src/app/system/scans/component.ts
=> Issue 176 - Scans name column filtering not usable

projects/developer/src/app/configuration/recipe-types/component.ts
=> Issue 182 - Recipe validation warning if name is not an existing recipe - UI temporary fix

projects/developer/src/app/system/strikes/component.scss
=> Issue 184 - Strike editing in dark theme 

projects/developer/src/app/system/scans/details.component.ts, projects/developer/src/app/system/strikes/api.model.ts, projects/developer/src/app/system/strikes/component.ts
=> Issue 183 - Duplicate Strikes and Scans

api/data/ingests.json, projects/developer/src/app/data/ingest/api.model.ts, projects/developer/src/app/data/ingest/component.html
=> Issue 168 - Ingest records page shows only first result

projects/developer/src/app/common/components/recipe-graph/component.html, projects/developer/src/app/common/components/recipe-graph/component.ts
=> Issue 194 - Increase SVG skew on publisher job to 45 degrees

package-lock.json, projects/developer/src/app/system/scans/details.component.ts, projects/developer/src/app/system/workspaces/api.model.ts
=> Issue 188 - Scans Aren't Queued

Dockerfile, docker/README.md, docker/docker-entrypoint.sh, docker/nginx-template.conf, docker/nginx.conf
Coincides with https://github.com/ngageoint/scale/pull/1714. Both are necessary to have a proper deployment going forward.
=> Update environment variables for consistency with Scale deployment

projects/developer/src/app/app.component.spec.ts
=> Issue 221 - Jasmine timeout error

projects/developer/src/app/configuration/job-types/component.html, projects/developer/src/app/configuration/job-types/component.ts, projects/developer/src/app/configuration/recipe-types/component.html, projects/developer/src/app/configuration/recipe-types/component.ts, projects/developer/src/app/data/ingest/component.html, projects/developer/src/app/data/ingest/component.ts, projects/developer/src/app/processing/batches/component.ts, projects/developer/src/app/processing/job-type-history/component.html, projects/developer/src/app/processing/job-type-history/component.ts, projects/developer/src/app/processing/jobs/component.html, projects/developer/src/app/processing/jobs/component.ts, projects/developer/src/app/processing/queued-jobs/component.html, projects/developer/src/app/processing/queued-jobs/component.ts, projects/developer/src/app/processing/recipes/component.html, projects/developer/src/app/processing/recipes/component.ts, projects/developer/src/app/processing/running-jobs/component.html, projects/developer/src/app/processing/running-jobs/component.ts, projects/developer/src/app/system/scans/component.html, projects/developer/src/app/system/scans/component.ts, projects/developer/src/app/system/strikes/component.html, projects/developer/src/app/system/strikes/component.ts, projects/developer/src/app/system/workspaces/component.html, projects/developer/src/app/system/workspaces/component.ts
=> Issue 215 - Make links openable in separate tabs

projects/developer/src/app/system/nodes/component.ts
=> #244 - Fix nodes page 

projects/developer/src/app/system/workspaces/component.html
Closes #249.
A bit hacky, but this seems to be working for me.
=> Issue 249: conditionally require host path based on broker selection

projects/developer/src/app/app-routing.module.ts, projects/developer/src/app/app.component.ts
Closes #237 
Concept from [here](https://ultimatecourses.com/blog/dynamic-page-titles-angular-2-router-events).
=> Issue 237 - add page titles for each route

README.md
=> Issue 278 - Documentation for config values

projects/developer/src/app/system/workspaces/component.ts
=> remove broker creds when no input provided

projects/developer/src/app/configuration/job-types/create.component.html, projects/developer/src/app/configuration/job-types/create.component.ts
Closes #272 
You may want to look this one over, I don't fully understand if this was the right solution or not.
=> Issue 272 - Ensure that the interface section of the job manifest has the attributes

projects/developer/src/app/common/components/recipe-graph/component.html, projects/developer/src/app/configuration/recipe-types/component.ts
=> 315 - A Job Type with no interface breaks the Recipe Editor

projects/developer/src/app/processing/batches/component.html, projects/developer/src/app/processing/batches/details.component.html, projects/developer/src/app/processing/batches/details.component.ts
Fixes #310 
Also hides the batch create / edit buttons for now.
=> Issue 310 - Fix undefined error when navigating batch detail page

api/data/job-details/job-details13.json, api/data/job-type-details/no-input1.0.0.json, api/data/job-type-names.json, api/data/job-type-status.json, api/data/job-types.json, api/data/running-jobs.json, projects/developer/src/app/configuration/job-types/create.component.html, projects/developer/src/app/configuration/job-types/create.component.ts
Fixed bug where job types with no interface would throw errors when try to edit them and half the UI components would be missing. Also added a mock data job type (no-interface) to test with.
=> Fix for No Interface Jobs UI Bug

Dockerfile
=> Issue 321 - Default to auth enabled when running through docker

projects/developer/src/app/common/components/recipe-graph/component.html, projects/developer/src/app/common/components/recipe-graph/component.ts
=> Improved condition logic flow visibility

api/data/job-details/job-details13.json, api/data/job-type-details/no-input1.0.0.json, api/data/job-type-names.json, api/data/job-type-status.json, api/data/job-types.json, api/data/running-jobs.json, projects/developer/src/app/common/components/recipe-graph/component.ts
Fixing error when adding/removing a recipe job dependency to a job that has no interface.
=> Dependency Connection Issue

projects/developer/src/app/data/feed/component.ts, projects/developer/src/app/processing/job-type-history/component.ts
Correcting issue with Job Type History page not populating data. Requires the scale PR for updating the metrics to be fully functional.
Closes #283
=> Issue 283 - Fixes Job Type History view

projects/developer/src/app/system/nodes/component.html, projects/developer/src/app/system/nodes/component.ts
Fixes issue where the context menu was always applying the action to the first node rather than the currently selected node.
=> Fix node action menu

projects/developer/src/app/processing/recipes/details.component.ts, proxy.conf.json
Fix Recipe Instance Display Issues
=> Recipe instance display issues

projects/developer/src/app/common/components/recipe-graph/component.html, projects/developer/src/app/common/components/recipe-graph/component.ts, projects/developer/src/app/configuration/recipe-types/component.html, projects/developer/src/app/configuration/recipe-types/component.ts, projects/developer/src/app/configuration/recipe-types/condition.component.html, projects/developer/src/app/configuration/recipe-types/condition.component.ts, projects/developer/src/app/configuration/recipe-types/filter.component.ts
Tracking in devops#374.
- removes required validation for filter values
- fix for adding dependency to condition node
- to reproduce:
1. add condition node
2. add job node
3. click condition node, add dependency to job node
4. this failed before
- please double check that this still works with recipes
=> Recipe conditions fixes

api/data/recipe-details/recipe-details3.json, api/data/recipe-type-details/recipe-type-details-worldview.json, api/data/recipe-types.json, projects/developer/src/app/common/components/recipe-graph/component.ts
added sub recipe to "worldview" recipe, subrecipes now use title instead of name for their label.
=> issue 374 - Display Recipe Type Name in the Graph

projects/developer/src/app/common/components/temporal-filter/component.html, projects/developer/src/app/common/components/temporal-filter/component.ts, projects/developer/src/app/data/ingest/component.html, projects/developer/src/app/data/ingest/component.ts, projects/developer/src/app/processing/batches/component.html, projects/developer/src/app/processing/batches/component.ts, projects/developer/src/app/processing/jobs/component.html, projects/developer/src/app/processing/jobs/component.ts, projects/developer/src/app/processing/recipes/component.html, projects/developer/src/app/processing/recipes/component.ts, projects/developer/src/app/system/scans/component.html, projects/developer/src/app/system/scans/component.ts
=> Issue 392 - loading state for temporal filter in live range mode

projects/developer/src/app/processing/batches/api.model.ts
=> Issue 395 - Round batches completion percentage to two decimals

projects/developer/src/app/common/components/temporal-filter/component.ts, projects/developer/src/app/common/utils/localstorage.ts, projects/developer/src/app/data/ingest/datatable.service.ts, projects/developer/src/app/processing/batches/datatable.service.ts, projects/developer/src/app/processing/jobs/datatable.service.ts, projects/developer/src/app/processing/recipes/datatable.service.ts, projects/developer/src/app/system/scans/datatable.service.ts
=> Issue 390 - save datatable options to local storage

projects/developer/src/app/processing/jobs/component.ts
=> Issue 398 - Job Types selection duplicating

projects/developer/src/app/processing/jobs/details.component.ts
I feel like this was too simple but it seems to work on Alpha 
fixes #420
=> Issue 420 - Fix job timeline

projects/developer/src/app/processing/jobs/component.html, projects/developer/src/app/processing/jobs/component.ts
=> Issue 425 - Show Node in Jobs table

projects/developer/src/app/processing/jobs/component.html, projects/developer/src/app/processing/jobs/details.component.ts
=> Issue 430 - Fix Jobs Table Errors

projects/developer/src/app/processing/batches/batches-component.ts, projects/developer/src/app/processing/recipes/component.ts
fixes #428 for recipes and batches table
=> issue 428 - Recipe Type duplication in dropdown

projects/developer/src/app/processing/jobs/component.scss
=> Issue 417 - Highlight table rows that have been visited

api/handlers/files.js, projects/developer/src/app/common/services/files/api.service.ts, projects/developer/src/app/processing/batches/batch-workflow/create-batch/create-batch.component.html, projects/developer/src/app/processing/batches/batch-workflow/create-batch/create-batch.component.ts, projects/developer/src/app/processing/batches/batch-workflow/create-dataset/create-dataset.component.html, projects/developer/src/app/processing/batches/batch-workflow/create-dataset/create-dataset.component.ts, projects/developer/src/app/processing/batches/batch-workflow/run-batch/run-batch.component.ts
* Removes required class and validator from create-batch priority form control.
* Adds created time filtering in addition to data time filtering.
=> Issue-10 Batches UI Bugfix

projects/developer/src/app/data/metrics/chart.service.ts
Fixes #443 and #444 
They both ended up being the same issue and it was just about the order of what was being filtered first
=> Issue #443 & #444 - Metrics (Job Types) not calculating correctly/Metrics (Errors) inconsistent data

projects/developer/src/app/dashboard/component.html, projects/developer/src/app/dashboard/component.ts
=> Issue 440 - Pie chart Label for favorites

projects/developer/src/app/processing/batches/batch-workflow/create-dataset/create-dataset.component.html, projects/developer/src/app/processing/batches/batch-workflow/create-dataset/create-dataset.component.ts
* Adds empty datatable message
* Change datatable label and display condition
=> Issue-463 Display Data Files table when no results returned

projects/developer/src/app/configuration/job-types/component.ts
=> Issue 287 - Add link to filtered jobs data table from job types detail view

projects/developer/src/app/processing/jobs/component.html, projects/developer/src/app/processing/jobs/component.ts
=> Issue 295 - Display star icon next to job type in datatable if it's a favorite

projects/developer/src/app/processing/jobs/component.ts
fixes #480 
I was going to do this and the tool tip in one PR but Emily and I aren't sure how to fix the table completely based on Chris' comments
=> Made column unsortable

api/handlers/jobs.js, projects/developer/src/app/processing/jobs/component.html, projects/developer/src/app/processing/jobs/component.scss, projects/developer/src/app/processing/jobs/component.ts
=> Issue 479 - Inputs tool tip overflowing

projects/developer/src/app/common/components/recipe-graph/component.ts, scale.code-workspace
After modal close and reopen, both inputs now show in recipe builder,  even if it is the same input file for both. Close #490
=> Issue #490 one file input set to both job inputs not showing in recipe builder

projects/developer/src/app/processing/jobs/component.ts
Jobs are now sortable by duration. 
https://github.com/ngageoint/scale/issues/1867
=> Job duration is now a sortable column

projects/developer/src/app/common/components/queue-load/component.ts, projects/developer/src/app/common/components/recipe-graph/component.html, projects/developer/src/app/common/components/recipe-graph/component.ts, projects/developer/src/app/common/services/color.service.ts, projects/developer/src/app/dashboard/data-feed/component.ts, projects/developer/src/app/dashboard/job-history/component.ts, projects/developer/src/app/data/feed/component.ts, projects/developer/src/app/data/metrics/component.ts, projects/developer/src/app/data/timeline/component.html, projects/developer/src/app/data/timeline/component.ts, projects/developer/src/app/processing/jobs/details.component.html, projects/developer/src/app/processing/jobs/details.component.ts, projects/developer/src/app/system/nodes/component.html, projects/developer/src/app/system/nodes/component.scss, projects/developer/src/app/system/nodes/component.ts
Added theme switching to chart text (ticks, legends, titles, etc.). Addresses issue [#487](https://github.com/ngageoint/scale-ui/issues/487)
=> Chart text

projects/developer/src/app/common/components/recipe-graph/component.ts
Fix #512,  but double arrow issue does remain.
=> Issue #512 Condition nodes detach when set as dependency

projects/developer/src/app/app.module.ts, projects/developer/src/app/auth.guard.ts, projects/developer/src/app/common/components/recipe-graph/component.ts
Fix #516 AuthGuard should work now.
=> Issue 516 - AuthGuard is failing

projects/developer/src/app/data/ingest/details.component.ts, projects/developer/src/app/processing/batches/batch-workflow/create-dataset/create-dataset.component.ts
fix linting erroring already done on high side
=> PR mirrorsync20220111

projects/developer/src/app/data/metrics/chart.service.ts
=> PR issue #559
